### ISSUE TITLE
Fatal error: Class 'WyriHaximus\HtmlCompress\Factory' not found in

### ISSUE THREAD

**Issue by loopion** [paramonovav/spress-html-compress#1]
I keep having this strangely and for my other plugins which depends on other packages does work. Can't find out what is going wrong:

Fatal error: Class 'WyriHaximus\HtmlCompress\Factory' not found in C:\Users\johndoe\dev\src\plugins\paramonovav\spress-html-compress\ParamonovavSpressHtmlCompress.php on line 53

I've tried on another system and it's the same result.

**Comment by paramonovav** [comment]
try
`composer require wyrihaximus/html-compress`

**Comment by loopion** [comment]
still nothing.

Just thought that this is maybe because I'm using the Spress.phar and not the full clone repo.

After doing what you said:

```
λ composer.bat require wyrihaximus/html-compress
Using version ^1.2 for wyrihaximus/html-compress
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
```

Don't know if it helps but I'm on Windows also.

**Comment by loopion** [comment]
Ok I confirm that it works when you have a full install and not only the spress.phar.

I've tested with a full install on my personal hosting and it worked perfectly.

Maybe you can just update the documentation in order to mention that it doesn't work with the phar install that's it.

Awesome work!

Thanks
